//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremiumBlack.Service.WCF
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EncryptedClass", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PremiumBlack.Service.WCF.IsTransactionConfirmedResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PremiumBlack.Service.WCF.CreateTransactionRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PremiumBlack.Service.WCF.CreateTransactionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PremiumBlack.Service.WCF.ActivateTransactionRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PremiumBlack.Service.WCF.ActivateTransactionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PremiumBlack.Service.WCF.GetTransactionDetailsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PremiumBlack.Service.WCF.GetTransactionDetailsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PremiumBlack.Service.WCF.GetTransactionByHashRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PremiumBlack.Service.WCF.GetTransactionByHashResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PremiumBlack.Service.WCF.GetTransactionsByAddressRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PremiumBlack.Service.WCF.GetTransactionsByAddressResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PremiumBlack.Service.WCF.CancelTransactionRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PremiumBlack.Service.WCF.CancelTransactionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PremiumBlack.Service.WCF.RateRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PremiumBlack.Service.WCF.RateResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PremiumBlack.Service.WCF.ReOpenTransactionRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PremiumBlack.Service.WCF.ReOpenTransactionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PremiumBlack.Service.WCF.IsTransactionConfirmedRequest))]
    public partial class EncryptedClass : object
    {
        
        private string ErrorField;
        
        private string HashField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hash
        {
            get
            {
                return this.HashField;
            }
            set
            {
                this.HashField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IsTransactionConfirmedResponse", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class IsTransactionConfirmedResponse : PremiumBlack.Service.WCF.EncryptedClass
    {
        
        private string ResultField;
        
        private string TransactionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateTransactionRequest", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class CreateTransactionRequest : PremiumBlack.Service.WCF.EncryptedClass
    {
        
        private string AmountField;
        
        private string BlockAddressField;
        
        private string CurrencyField;
        
        private string CustomDataField;
        
        private string CustomOrderIdField;
        
        private string CustomUserIdField;
        
        private string CustomerMailField;
        
        private string IPNField;
        
        private string PriceCurrencyField;
        
        private bool ReturnQRCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlockAddress
        {
            get
            {
                return this.BlockAddressField;
            }
            set
            {
                this.BlockAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomData
        {
            get
            {
                return this.CustomDataField;
            }
            set
            {
                this.CustomDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomOrderId
        {
            get
            {
                return this.CustomOrderIdField;
            }
            set
            {
                this.CustomOrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomUserId
        {
            get
            {
                return this.CustomUserIdField;
            }
            set
            {
                this.CustomUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerMail
        {
            get
            {
                return this.CustomerMailField;
            }
            set
            {
                this.CustomerMailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPN
        {
            get
            {
                return this.IPNField;
            }
            set
            {
                this.IPNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceCurrency
        {
            get
            {
                return this.PriceCurrencyField;
            }
            set
            {
                this.PriceCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReturnQRCode
        {
            get
            {
                return this.ReturnQRCodeField;
            }
            set
            {
                this.ReturnQRCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateTransactionResponse", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class CreateTransactionResponse : PremiumBlack.Service.WCF.EncryptedClass
    {
        
        private string AddressToReceiveField;
        
        private bool AllowOverpayField;
        
        private bool AllowUnderpayField;
        
        private string AmountField;
        
        private string CurrencyField;
        
        private PremiumBlack.Service.WCF.ExchangeData ExchangeField;
        
        private string OriginalAmountField;
        
        private string PricingCurrencyField;
        
        private string QRCodeField;
        
        private string StatusField;
        
        private string TransactionIdField;
        
        private string TransactionKeyField;
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressToReceive
        {
            get
            {
                return this.AddressToReceiveField;
            }
            set
            {
                this.AddressToReceiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowOverpay
        {
            get
            {
                return this.AllowOverpayField;
            }
            set
            {
                this.AllowOverpayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowUnderpay
        {
            get
            {
                return this.AllowUnderpayField;
            }
            set
            {
                this.AllowUnderpayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PremiumBlack.Service.WCF.ExchangeData Exchange
        {
            get
            {
                return this.ExchangeField;
            }
            set
            {
                this.ExchangeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalAmount
        {
            get
            {
                return this.OriginalAmountField;
            }
            set
            {
                this.OriginalAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PricingCurrency
        {
            get
            {
                return this.PricingCurrencyField;
            }
            set
            {
                this.PricingCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QRCode
        {
            get
            {
                return this.QRCodeField;
            }
            set
            {
                this.QRCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionKey
        {
            get
            {
                return this.TransactionKeyField;
            }
            set
            {
                this.TransactionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivateTransactionRequest", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class ActivateTransactionRequest : PremiumBlack.Service.WCF.EncryptedClass
    {
        
        private string TransactionIdField;
        
        private string TransactionKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionKey
        {
            get
            {
                return this.TransactionKeyField;
            }
            set
            {
                this.TransactionKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivateTransactionResponse", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class ActivateTransactionResponse : PremiumBlack.Service.WCF.EncryptedClass
    {
        
        private string ResultField;
        
        private string TransactionIdField;
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTransactionDetailsRequest", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class GetTransactionDetailsRequest : PremiumBlack.Service.WCF.EncryptedClass
    {
        
        private bool ReturnQRCodeField;
        
        private string TransactionIdField;
        
        private string TransactionKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReturnQRCode
        {
            get
            {
                return this.ReturnQRCodeField;
            }
            set
            {
                this.ReturnQRCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionKey
        {
            get
            {
                return this.TransactionKeyField;
            }
            set
            {
                this.TransactionKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTransactionDetailsResponse", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class GetTransactionDetailsResponse : PremiumBlack.Service.WCF.EncryptedClass
    {
        
        private string AddressToReceiveField;
        
        private bool AllowOverpayField;
        
        private bool AllowUnderpayField;
        
        private string AmountField;
        
        private System.Nullable<System.DateTime> CanceledAtField;
        
        private string ChangedAmountField;
        
        private string ChangedOriginalAmountField;
        
        private long ConfirmationsField;
        
        private System.Nullable<System.DateTime> ConfirmedAtField;
        
        private System.DateTime CreatedAtField;
        
        private string CurrencyField;
        
        private string CustomDataField;
        
        private string CustomOrderIdField;
        
        private string CustomUserIdField;
        
        private string CustomerMailField;
        
        private PremiumBlack.Service.WCF.ExchangeData ExchangeField;
        
        private System.Nullable<System.DateTime> ExpiresAtField;
        
        private PremiumBlack.Service.WCF.IncomeEntry[] IncomesField;
        
        private string OriginalAmountField;
        
        private string PricingCurrencyField;
        
        private string QRCodeField;
        
        private string ReceivedAmountField;
        
        private string StatusField;
        
        private string TransactionIdField;
        
        private string TransactionKeyField;
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressToReceive
        {
            get
            {
                return this.AddressToReceiveField;
            }
            set
            {
                this.AddressToReceiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowOverpay
        {
            get
            {
                return this.AllowOverpayField;
            }
            set
            {
                this.AllowOverpayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowUnderpay
        {
            get
            {
                return this.AllowUnderpayField;
            }
            set
            {
                this.AllowUnderpayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CanceledAt
        {
            get
            {
                return this.CanceledAtField;
            }
            set
            {
                this.CanceledAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChangedAmount
        {
            get
            {
                return this.ChangedAmountField;
            }
            set
            {
                this.ChangedAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChangedOriginalAmount
        {
            get
            {
                return this.ChangedOriginalAmountField;
            }
            set
            {
                this.ChangedOriginalAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Confirmations
        {
            get
            {
                return this.ConfirmationsField;
            }
            set
            {
                this.ConfirmationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ConfirmedAt
        {
            get
            {
                return this.ConfirmedAtField;
            }
            set
            {
                this.ConfirmedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomData
        {
            get
            {
                return this.CustomDataField;
            }
            set
            {
                this.CustomDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomOrderId
        {
            get
            {
                return this.CustomOrderIdField;
            }
            set
            {
                this.CustomOrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomUserId
        {
            get
            {
                return this.CustomUserIdField;
            }
            set
            {
                this.CustomUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerMail
        {
            get
            {
                return this.CustomerMailField;
            }
            set
            {
                this.CustomerMailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PremiumBlack.Service.WCF.ExchangeData Exchange
        {
            get
            {
                return this.ExchangeField;
            }
            set
            {
                this.ExchangeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpiresAt
        {
            get
            {
                return this.ExpiresAtField;
            }
            set
            {
                this.ExpiresAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PremiumBlack.Service.WCF.IncomeEntry[] Incomes
        {
            get
            {
                return this.IncomesField;
            }
            set
            {
                this.IncomesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalAmount
        {
            get
            {
                return this.OriginalAmountField;
            }
            set
            {
                this.OriginalAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PricingCurrency
        {
            get
            {
                return this.PricingCurrencyField;
            }
            set
            {
                this.PricingCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QRCode
        {
            get
            {
                return this.QRCodeField;
            }
            set
            {
                this.QRCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceivedAmount
        {
            get
            {
                return this.ReceivedAmountField;
            }
            set
            {
                this.ReceivedAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionKey
        {
            get
            {
                return this.TransactionKeyField;
            }
            set
            {
                this.TransactionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTransactionByHashRequest", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class GetTransactionByHashRequest : PremiumBlack.Service.WCF.EncryptedClass
    {
        
        private string CurrencyField;
        
        private string HashIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HashId
        {
            get
            {
                return this.HashIdField;
            }
            set
            {
                this.HashIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTransactionByHashResponse", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class GetTransactionByHashResponse : PremiumBlack.Service.WCF.EncryptedClass
    {
        
        private PremiumBlack.Service.WCF.GetTransactionDetailsResponse TransactionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PremiumBlack.Service.WCF.GetTransactionDetailsResponse Transaction
        {
            get
            {
                return this.TransactionField;
            }
            set
            {
                this.TransactionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTransactionsByAddressRequest", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class GetTransactionsByAddressRequest : PremiumBlack.Service.WCF.EncryptedClass
    {
        
        private string AddressField;
        
        private string CurrencyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTransactionsByAddressResponse", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class GetTransactionsByAddressResponse : PremiumBlack.Service.WCF.EncryptedClass
    {
        
        private string AddressField;
        
        private int CountField;
        
        private PremiumBlack.Service.WCF.GetTransactionDetailsResponse[] TransactionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count
        {
            get
            {
                return this.CountField;
            }
            set
            {
                this.CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PremiumBlack.Service.WCF.GetTransactionDetailsResponse[] Transactions
        {
            get
            {
                return this.TransactionsField;
            }
            set
            {
                this.TransactionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelTransactionRequest", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class CancelTransactionRequest : PremiumBlack.Service.WCF.EncryptedClass
    {
        
        private string ByCustomerField;
        
        private string TransactionIdField;
        
        private string TransactionKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ByCustomer
        {
            get
            {
                return this.ByCustomerField;
            }
            set
            {
                this.ByCustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionKey
        {
            get
            {
                return this.TransactionKeyField;
            }
            set
            {
                this.TransactionKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelTransactionResponse", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class CancelTransactionResponse : PremiumBlack.Service.WCF.EncryptedClass
    {
        
        private string ResultField;
        
        private string TransactionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RateRequest", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class RateRequest : PremiumBlack.Service.WCF.EncryptedClass
    {
        
        private string ExchangeIDField;
        
        private string FromCurrencyField;
        
        private string ToCurrencyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExchangeID
        {
            get
            {
                return this.ExchangeIDField;
            }
            set
            {
                this.ExchangeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromCurrency
        {
            get
            {
                return this.FromCurrencyField;
            }
            set
            {
                this.FromCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToCurrency
        {
            get
            {
                return this.ToCurrencyField;
            }
            set
            {
                this.ToCurrencyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RateResponse", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class RateResponse : PremiumBlack.Service.WCF.EncryptedClass
    {
        
        private PremiumBlack.Service.WCF.ExchangeData ExchangeField;
        
        private string FromCurrencyField;
        
        private string RateValueField;
        
        private string ToCurrencyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PremiumBlack.Service.WCF.ExchangeData Exchange
        {
            get
            {
                return this.ExchangeField;
            }
            set
            {
                this.ExchangeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromCurrency
        {
            get
            {
                return this.FromCurrencyField;
            }
            set
            {
                this.FromCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RateValue
        {
            get
            {
                return this.RateValueField;
            }
            set
            {
                this.RateValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToCurrency
        {
            get
            {
                return this.ToCurrencyField;
            }
            set
            {
                this.ToCurrencyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReOpenTransactionRequest", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class ReOpenTransactionRequest : PremiumBlack.Service.WCF.EncryptedClass
    {
        
        private string TransactionIdField;
        
        private string TransactionKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionKey
        {
            get
            {
                return this.TransactionKeyField;
            }
            set
            {
                this.TransactionKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReOpenTransactionResponse", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class ReOpenTransactionResponse : PremiumBlack.Service.WCF.EncryptedClass
    {
        
        private string ResultField;
        
        private string TransactionIdField;
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IsTransactionConfirmedRequest", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class IsTransactionConfirmedRequest : PremiumBlack.Service.WCF.EncryptedClass
    {
        
        private string TransactionIdField;
        
        private string TransactionKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionKey
        {
            get
            {
                return this.TransactionKeyField;
            }
            set
            {
                this.TransactionKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExchangeData", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class ExchangeData : object
    {
        
        private decimal ExchangeRateField;
        
        private string IDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ExchangeRate
        {
            get
            {
                return this.ExchangeRateField;
            }
            set
            {
                this.ExchangeRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IncomeEntry", Namespace="http://schemas.datacontract.org/2004/07/Plattform.service")]
    public partial class IncomeEntry : object
    {
        
        private string AmountField;
        
        private string TXHashField;
        
        private string TimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TXHash
        {
            get
            {
                return this.TXHashField;
            }
            set
            {
                this.TXHashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PremiumBlack.Service.WCF.IPay")]
    public interface IPay
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/IsTransactionConfirmed", ReplyAction="http://tempuri.org/IPay/IsTransactionConfirmedResponse")]
        PremiumBlack.Service.WCF.IsTransactionConfirmedResponse IsTransactionConfirmed(string publicKey, PremiumBlack.Service.WCF.IsTransactionConfirmedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/IsTransactionConfirmed", ReplyAction="http://tempuri.org/IPay/IsTransactionConfirmedResponse")]
        System.Threading.Tasks.Task<PremiumBlack.Service.WCF.IsTransactionConfirmedResponse> IsTransactionConfirmedAsync(string publicKey, PremiumBlack.Service.WCF.IsTransactionConfirmedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/CreateTransaction", ReplyAction="http://tempuri.org/IPay/CreateTransactionResponse")]
        PremiumBlack.Service.WCF.CreateTransactionResponse CreateTransaction(string publicKey, PremiumBlack.Service.WCF.CreateTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/CreateTransaction", ReplyAction="http://tempuri.org/IPay/CreateTransactionResponse")]
        System.Threading.Tasks.Task<PremiumBlack.Service.WCF.CreateTransactionResponse> CreateTransactionAsync(string publicKey, PremiumBlack.Service.WCF.CreateTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/ActivateTransaction", ReplyAction="http://tempuri.org/IPay/ActivateTransactionResponse")]
        PremiumBlack.Service.WCF.ActivateTransactionResponse ActivateTransaction(string publicKey, PremiumBlack.Service.WCF.ActivateTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/ActivateTransaction", ReplyAction="http://tempuri.org/IPay/ActivateTransactionResponse")]
        System.Threading.Tasks.Task<PremiumBlack.Service.WCF.ActivateTransactionResponse> ActivateTransactionAsync(string publicKey, PremiumBlack.Service.WCF.ActivateTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/GetTransactionDetails", ReplyAction="http://tempuri.org/IPay/GetTransactionDetailsResponse")]
        PremiumBlack.Service.WCF.GetTransactionDetailsResponse GetTransactionDetails(string publicKey, PremiumBlack.Service.WCF.GetTransactionDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/GetTransactionDetails", ReplyAction="http://tempuri.org/IPay/GetTransactionDetailsResponse")]
        System.Threading.Tasks.Task<PremiumBlack.Service.WCF.GetTransactionDetailsResponse> GetTransactionDetailsAsync(string publicKey, PremiumBlack.Service.WCF.GetTransactionDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/GetTransactionByHash", ReplyAction="http://tempuri.org/IPay/GetTransactionByHashResponse")]
        PremiumBlack.Service.WCF.GetTransactionByHashResponse GetTransactionByHash(string publicKey, PremiumBlack.Service.WCF.GetTransactionByHashRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/GetTransactionByHash", ReplyAction="http://tempuri.org/IPay/GetTransactionByHashResponse")]
        System.Threading.Tasks.Task<PremiumBlack.Service.WCF.GetTransactionByHashResponse> GetTransactionByHashAsync(string publicKey, PremiumBlack.Service.WCF.GetTransactionByHashRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/GetTransactionsByAddress", ReplyAction="http://tempuri.org/IPay/GetTransactionsByAddressResponse")]
        PremiumBlack.Service.WCF.GetTransactionsByAddressResponse GetTransactionsByAddress(string publicKey, PremiumBlack.Service.WCF.GetTransactionsByAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/GetTransactionsByAddress", ReplyAction="http://tempuri.org/IPay/GetTransactionsByAddressResponse")]
        System.Threading.Tasks.Task<PremiumBlack.Service.WCF.GetTransactionsByAddressResponse> GetTransactionsByAddressAsync(string publicKey, PremiumBlack.Service.WCF.GetTransactionsByAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/CancelTransaction", ReplyAction="http://tempuri.org/IPay/CancelTransactionResponse")]
        PremiumBlack.Service.WCF.CancelTransactionResponse CancelTransaction(string publicKey, PremiumBlack.Service.WCF.CancelTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/CancelTransaction", ReplyAction="http://tempuri.org/IPay/CancelTransactionResponse")]
        System.Threading.Tasks.Task<PremiumBlack.Service.WCF.CancelTransactionResponse> CancelTransactionAsync(string publicKey, PremiumBlack.Service.WCF.CancelTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/GetRate", ReplyAction="http://tempuri.org/IPay/GetRateResponse")]
        PremiumBlack.Service.WCF.RateResponse GetRate(string publicKey, PremiumBlack.Service.WCF.RateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/GetRate", ReplyAction="http://tempuri.org/IPay/GetRateResponse")]
        System.Threading.Tasks.Task<PremiumBlack.Service.WCF.RateResponse> GetRateAsync(string publicKey, PremiumBlack.Service.WCF.RateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/ReOpenTransaction", ReplyAction="http://tempuri.org/IPay/ReOpenTransactionResponse")]
        PremiumBlack.Service.WCF.ReOpenTransactionResponse ReOpenTransaction(string publicKey, PremiumBlack.Service.WCF.ReOpenTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/ReOpenTransaction", ReplyAction="http://tempuri.org/IPay/ReOpenTransactionResponse")]
        System.Threading.Tasks.Task<PremiumBlack.Service.WCF.ReOpenTransactionResponse> ReOpenTransactionAsync(string publicKey, PremiumBlack.Service.WCF.ReOpenTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/Test", ReplyAction="http://tempuri.org/IPay/TestResponse")]
        string Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPay/Test", ReplyAction="http://tempuri.org/IPay/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IPayChannel : PremiumBlack.Service.WCF.IPay, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PayClient : System.ServiceModel.ClientBase<PremiumBlack.Service.WCF.IPay>, PremiumBlack.Service.WCF.IPay
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PayClient() : 
                base(PayClient.GetDefaultBinding(), PayClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPay.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PayClient(EndpointConfiguration endpointConfiguration) : 
                base(PayClient.GetBindingForEndpoint(endpointConfiguration), PayClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PayClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PayClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PayClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PayClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PremiumBlack.Service.WCF.IsTransactionConfirmedResponse IsTransactionConfirmed(string publicKey, PremiumBlack.Service.WCF.IsTransactionConfirmedRequest request)
        {
            return base.Channel.IsTransactionConfirmed(publicKey, request);
        }
        
        public System.Threading.Tasks.Task<PremiumBlack.Service.WCF.IsTransactionConfirmedResponse> IsTransactionConfirmedAsync(string publicKey, PremiumBlack.Service.WCF.IsTransactionConfirmedRequest request)
        {
            return base.Channel.IsTransactionConfirmedAsync(publicKey, request);
        }
        
        public PremiumBlack.Service.WCF.CreateTransactionResponse CreateTransaction(string publicKey, PremiumBlack.Service.WCF.CreateTransactionRequest request)
        {
            return base.Channel.CreateTransaction(publicKey, request);
        }
        
        public System.Threading.Tasks.Task<PremiumBlack.Service.WCF.CreateTransactionResponse> CreateTransactionAsync(string publicKey, PremiumBlack.Service.WCF.CreateTransactionRequest request)
        {
            return base.Channel.CreateTransactionAsync(publicKey, request);
        }
        
        public PremiumBlack.Service.WCF.ActivateTransactionResponse ActivateTransaction(string publicKey, PremiumBlack.Service.WCF.ActivateTransactionRequest request)
        {
            return base.Channel.ActivateTransaction(publicKey, request);
        }
        
        public System.Threading.Tasks.Task<PremiumBlack.Service.WCF.ActivateTransactionResponse> ActivateTransactionAsync(string publicKey, PremiumBlack.Service.WCF.ActivateTransactionRequest request)
        {
            return base.Channel.ActivateTransactionAsync(publicKey, request);
        }
        
        public PremiumBlack.Service.WCF.GetTransactionDetailsResponse GetTransactionDetails(string publicKey, PremiumBlack.Service.WCF.GetTransactionDetailsRequest request)
        {
            return base.Channel.GetTransactionDetails(publicKey, request);
        }
        
        public System.Threading.Tasks.Task<PremiumBlack.Service.WCF.GetTransactionDetailsResponse> GetTransactionDetailsAsync(string publicKey, PremiumBlack.Service.WCF.GetTransactionDetailsRequest request)
        {
            return base.Channel.GetTransactionDetailsAsync(publicKey, request);
        }
        
        public PremiumBlack.Service.WCF.GetTransactionByHashResponse GetTransactionByHash(string publicKey, PremiumBlack.Service.WCF.GetTransactionByHashRequest request)
        {
            return base.Channel.GetTransactionByHash(publicKey, request);
        }
        
        public System.Threading.Tasks.Task<PremiumBlack.Service.WCF.GetTransactionByHashResponse> GetTransactionByHashAsync(string publicKey, PremiumBlack.Service.WCF.GetTransactionByHashRequest request)
        {
            return base.Channel.GetTransactionByHashAsync(publicKey, request);
        }
        
        public PremiumBlack.Service.WCF.GetTransactionsByAddressResponse GetTransactionsByAddress(string publicKey, PremiumBlack.Service.WCF.GetTransactionsByAddressRequest request)
        {
            return base.Channel.GetTransactionsByAddress(publicKey, request);
        }
        
        public System.Threading.Tasks.Task<PremiumBlack.Service.WCF.GetTransactionsByAddressResponse> GetTransactionsByAddressAsync(string publicKey, PremiumBlack.Service.WCF.GetTransactionsByAddressRequest request)
        {
            return base.Channel.GetTransactionsByAddressAsync(publicKey, request);
        }
        
        public PremiumBlack.Service.WCF.CancelTransactionResponse CancelTransaction(string publicKey, PremiumBlack.Service.WCF.CancelTransactionRequest request)
        {
            return base.Channel.CancelTransaction(publicKey, request);
        }
        
        public System.Threading.Tasks.Task<PremiumBlack.Service.WCF.CancelTransactionResponse> CancelTransactionAsync(string publicKey, PremiumBlack.Service.WCF.CancelTransactionRequest request)
        {
            return base.Channel.CancelTransactionAsync(publicKey, request);
        }
        
        public PremiumBlack.Service.WCF.RateResponse GetRate(string publicKey, PremiumBlack.Service.WCF.RateRequest request)
        {
            return base.Channel.GetRate(publicKey, request);
        }
        
        public System.Threading.Tasks.Task<PremiumBlack.Service.WCF.RateResponse> GetRateAsync(string publicKey, PremiumBlack.Service.WCF.RateRequest request)
        {
            return base.Channel.GetRateAsync(publicKey, request);
        }
        
        public PremiumBlack.Service.WCF.ReOpenTransactionResponse ReOpenTransaction(string publicKey, PremiumBlack.Service.WCF.ReOpenTransactionRequest request)
        {
            return base.Channel.ReOpenTransaction(publicKey, request);
        }
        
        public System.Threading.Tasks.Task<PremiumBlack.Service.WCF.ReOpenTransactionResponse> ReOpenTransactionAsync(string publicKey, PremiumBlack.Service.WCF.ReOpenTransactionRequest request)
        {
            return base.Channel.ReOpenTransactionAsync(publicKey, request);
        }
        
        public string Test()
        {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<string> TestAsync()
        {
            return base.Channel.TestAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPay))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPay))
            {
                return new System.ServiceModel.EndpointAddress("https://premium.black/service/wcf/Pay.svc");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PayClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPay);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PayClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPay);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPay,
        }
    }
}
